### ISSUE TITLE
Could not find active peak

### ISSUE THREAD

**Issue by drooff** [jrfernandes/ontario_energy_board#2] opened 2022-02-08 18:36 UTC
I just installed this integration and it isn't able to retrieve the current peak information, suggesting maybe the webpage layout has changed. My utility was listed properly during the setup of the integration, but the sensor value is never populated.

Error log:
```
This error originated from a custom integration.

Logger: custom_components.ontario_energy_board.api
Source: custom_components/ontario_energy_board/api.py:101
Integration: Ontario Energy Board (documentation, issues)
First occurred: 12:41:50 PM (10 occurrences)
Last logged: 1:27:22 PM

Could not find active peak. Perhaps the webpage layout has changed
```

Thanks for building this, if it works it saves me a lot of time and effort doing it the hard way with utility meter and tariff components!

**Comment by kwkid** [comment] 2022-02-08 22:38
droff:
Your comment regarding the utility meter caught my eye. Based on my experience with this component it simply reports on the $ kWh rate charged during the appropriate timed tiers…the utility meter still plays a role and perhaps the integration component in calculating the daily and monthly $ consumption values.
I guess you can have an automation trigger on the state of this component..if you capture the old and new values you can calculate your consumption based on the kWh change over the period…perhaps I am missing something in how this component was intended to be used…can you share your insight on how you intend to use this…

**Comment by jrfernandes** [comment] 2022-02-09 14:32
Unfortunately, it appears that that the OEB site no longer includes a page indicating the current peak. That didn't last long :/

The rates are still being pulled successfully, as it's part of their Open Data initiative. As for getting the current rate, we will need a new method to get that. I might take a shot at it during the weekend.

**Comment by jrfernandes** [comment] 2022-02-09 14:34
> droff:
> Your comment regarding the utility meter caught my eye. Based on my experience with this component it simply reports on the $ kWh rate charged during the appropriate timed tiers…the utility meter still plays a role and perhaps the integration component in calculating the daily and monthly $ consumption values.
> I guess you can have an automation trigger on the state of this component..if you capture the old and new values you can calculate your consumption based on the kWh change over the period…perhaps I am missing something in how this component was intended to be used…can you share your insight on how you intend to use this…

@kwkid - the way I'm using this component is with the Home Assistant's Energy monitoring functionality, where you can assign this sensor with any energy monitoring attribute you add there. It works great and no need for any automation or tariff settings madness as before.

**Comment by jrfernandes** [comment] 2022-02-10 00:28
The problem with that is that they're updating the value of that element via JS on the client-side. The HTML will always have `mid-peak` hard-coded.

**Comment by jrfernandes** [comment] 2022-02-11 17:55
@maxistviews - I thought about hard-coding it, the problem is that during the day the on-peak and mid-peak periods switch during winter time. I didn't research if it's always the same time of the year or not, but it will definitely make things tricky, especially when odd events happen, like when in 2020 Ontario applied a 24-hour fixed rate.

I do however have an idea on how to get the current peak leveraging the site of one of the hydro companies. We should have this working again this weekend.

**Comment by maxistviews** [comment] 2022-02-11 18:27
Great to hear it! 

I think as a safety measure fallback, I will hard code a sensor myself and then use it only if this integration fails again ;) The OEB website makes it pretty clear that summer and winter time periods have consistent peaks, so I'll use that for my sensor. 

Id be surprised if we'd get the 24 hour period again as that was just to do with the lockdown measures. But holidays that fall on weekends would need to be something to add to a hard coded sensor.

**Comment by jrfernandes** [comment] 2022-02-11 18:36
I remember reading that when holidays that fall on weekends the following Monday will be off-peak. Should be confirmed.

Though, I do like the idea of having a fallback in case integration can't reach the EOB or other website. I might include something for that as well.

**Comment by jrfernandes** [comment] 2022-02-12 06:41
This issue should now be solved and the sensor is working once again.

@maxistviews - I took your advise and just added logic to figure out the current peak without scrapping the web.

**Comment by kwkid** [comment] 2022-02-12 13:15
Life is good...Thx for resolving the issue. Much appreciated

**Comment by maxistviews** [comment] 2022-02-12 14:25
That's fantastic, thank you! :)

**Closed** 2022-02-12 14:34 UTC
